### ISSUE TITLE
Payment time states it's EPOCH

### ISSUE THREAD

**Issue by Prothon** [wizkid057/wizstats#19]
Recently after the last block matured I noticed that the latest payment was stated for 1970-01-01. 

It seems that the date scheduled for payment has forced it's self to epoch.

**Comment by wizkid057** [comment]
I noticed this.  It is an issue where the reward system does not record a "roundend" time for manual payouts (since the round didn't end...) and the stats are using that data from the JSON pool API to get the date.

I'll have to use an alternate method to get the time for manual payouts.

**Comment by wizkid057** [comment]
Issue fixed in commit 8936fb5039a8b96dc8e9cde91a453f9db3e96599 .  Thanks for the report! :)
