### ISSUE TITLE
Sorting by hashrate on the block list page sorts incorrectly

### ISSUE THREAD

**Issue by edgeman16** [wizkid057/wizstats#23]
On http://eligius.st/~wizkid057/newstats/blocks.php
if you sort by hashrate, it appears to sort alpha instead of numeric.

**Comment by wizkid057** [comment]
It does alpha sort actually. This wasn't an issue until we broke 1Th/sec. I will address this tonight.

**Comment by edgeman16** [comment]
That pesky comma :)  No worries, I was briefly confused when I sorted by hashrate and didn't see anything at the top above 1Th/s

**Comment by wizkid057** [comment]
Fixed in commit 77104c600447dbdf28e27d1035642a836cfc2cf5
Thanks for the report! :D
