### ISSUE TITLE
Top buttons overlap donation message at top of stats page

### ISSUE THREAD

**Issue by dmm** [wizkid057/wizstats#27]
Ubuntu 13.04
The problem exists in both FF 22 and chromium Version 28.0.1500.71.
![eligiusstats](https://f.cloud.github.com/assets/32881/880017/d6860358-f932-11e2-844b-923468043450.png)

**Comment by PwnicornDev** [comment]
I tried to reproduce this on Chrome and Firefox, everything is working here. Did you try it on a clean profile with default settings and without any extensions?

**Comment by wizkid057** [comment]
I think in general the stats could probably use a more universally supported layout.  For now I'm not going to worry much about these one-off browser issues.  The majority of people have no problems.
