### ISSUE TITLE
Separation of stats by worker

### ISSUE THREAD

**Issue by unordinateur** [wizkid057/wizstats#29]
Hi! I have a suggestion for a feature.
Currently, if I make all my workers work for my Eligius account, the stats give me an aggregated hashrate. There is no wahy of knowing if a given device has stopped producing shares. It would be greak if we could have stats per device.

Of course, I know that the server has no idea how to tell which worker sent a given share. My idea would be to use the password field from the login. Sice this field serves no purpuse here, I could identify each of my devices with a different login passoword, and the stats would be given separetaly for each.

Thanks, and great work!

**Comment by luke-jr** [comment]
Workers are already supported by the core pool by using an underscore separator. eg, 1youraddress_workername

Stats still don't handle it though :(

**Comment by wizkid057** [comment]
Been meaning to do this, just haven't gotten to it. :(

**Comment by unordinateur** [comment]
Well if the core already supports this, half's the job is done! :)

But you're doing a really good job, and the core feature work well, so no stress :)

**Comment by wizkid057** [comment]
This actually ended up being a priority today.  Most of the work is done.  Just going to whip up a table of workers later. :)

**Comment by unordinateur** [comment]
I juste tested the feature. Works great!
Thanks!
