### ISSUE TITLE
How come there isn't a balance-json.php to retrieve individual BTC balance?

### ISSUE THREAD

**Issue by mbrand1** [wizkid057/wizstats#34]
Is that something someone is working on or could I take a stab at it?

**Comment by luke-jr** [comment]
http://eligius.st/~luke-jr/balance.php?addr=1foo

**Comment by wizkid057** [comment]
As posted, Luke-Jr's original script still works, as the format of the balances.json file hasn't changed.  I'll probably add it to api.php anyway, though.

**Comment by mbrand1** [comment]
Ah, I was trying balance.php?address=.  Thanks.
