### ISSUE TITLE
Incorrect graph axis

### ISSUE THREAD

**Issue by jgillard** [wizkid057/wizstats#37]
I've just noticced this on the 2nd graph on my stats page.

![capture](https://f.cloud.github.com/assets/3770312/1350488/f5c638fc-370b-11e3-8470-7df3d4486a1e.PNG)

**Comment by gruppler** [comment]
I don't see anything wrong with this. 5.00e-3 is the same as 0.005.

**Comment by jgillard** [comment]
I was actually pointing out the repeated numbers, it could down with more decimal points

**Comment by gruppler** [comment]
So the number of digits shown should be a function of the maximum, related to the way the number of horizontal grid lines are determined.

**Comment by wizkid057** [comment]
This actually is an issue with dygraph I believe (the graphing library in use)
