### ISSUE TITLE
I made a simple javascript library

### ISSUE THREAD

**Issue by LinusU** [wizkid057/wizstats#45]
Hi Wizkid,

Thanks for providing a great service, I wrote up a quick javascript library for accessing your public api. It has good error handling, follows javascript callback best practices and doesn't depend on anything other than plain javascript.

https://gist.github.com/LinusU/7446896

Maybe we could distribute it in some good way to let more users get quickly started with building cool apps that uses your data? I wrote this since I wanted a quick html-file that just displayed my current hash-rate.

Thanks for your time!

A quick example of how the api works:

``` javascript
var u = prompt('What is you username?');

api.gethashrate({ username: u }, function (err, data) {
  if (err) {
    alert('Something went wrong!\n\n(' + err.message + ')');
  } else {
    alert('Your average hashing rate is: ' + data.av256.pretty);
  }
});
```

**Comment by wizkid057** [comment]
Not sure this is the right place for this, but, I'll try to find a home for it.

**Comment by LinusU** [comment]
Thanks, I really just felt like it would be better to have an available implementation that handles errors gracefully since that is what most developers tend to skip when just quickly putting something together. And things quickly put together has a tendency to become production code. :)

I also just uploaded some more improvements to the script. It now handels network errors (like the ones we are getting now because of your temporary takedown) and also pass jslint without any errors (assuming `browser: true`).
