### ISSUE TITLE
Is Eligius not meant for my miner?

### ISSUE THREAD

**Issue by dannymackny** [wizkid057/wizstats#50]
I'm using BFL's Little Single with BFGminer 3.6.0
Problem is my speed is as follows:
24.23/23.01/18.72
Given that the third has more to do with the pool, I was wondering if this pool is known to not maximize the hash rate for this asic.

Any thoughts?

**Comment by luke-jr** [comment]
If your reject rate is unusually high (over 1% or so), there might be a problem between the pool and your PC.
The third hashrate is also influenced by luck as well.

Eligius has a support webchat, maybe wizkid057 is around to troubleshoot with.

**Comment by dannymackny** [comment]
Thanks. Josh asked you about this on G+ and we got slapped with a RTFM...lol
So, we both did. Thanks for the great wares, bro. Much appreciated!
Accepted shares at 12959. My reject rate is (50) .41%...HW: 723/1.1

**Comment by luke-jr** [comment]
Ironically, I thought I was responding to a BFGMiner Issue here... Not sure why it's on wizstats >_<
Those numbers look normal for BFL stuff. Maybe just bad luck :(

**Comment by wizkid057** [comment]
While i dont believe there is an issue here Id be interested in the related eligius username in the interest of thoroughness.

**Comment by mtab3000** [comment]
Keep it stateless...

Thx

mtab3000@gmail.com

**Comment by gruppler** [comment]
FWIW, I'm also using a Little Single and my speed has consistently been 28.13/28.31/28.14Gh/s (with bfgminer 3.4.0).

**Comment by dannymackny** [comment]
If I pull the plug and reboot, do I risk looking anything from the pool?

**Comment by wizkid057** [comment]
You don't lose anything already submitted, you just lose the potential shares you can't submit while you're offline, obviously, as with any pool.

**Comment by wizkid057** [comment]
Going to close this since its not a stats issue.
