### ISSUE TITLE
Double Payout

### ISSUE THREAD

**Issue by vtsuei2** [wizkid057/wizstats#56]
A little under a week ago, got a double payout about 2 hours apart - both confirmed successfully (impossible for me to have mined that much). After that, unpaid balance was still increasing, but zeroed out after each block. 

http://eligius.st/~wizkid057/newstats/userstats.php/19BnTKVtn2hYR8S4KD3zUgUwHSCYEXc4Ys

**Comment by wizkid057** [comment]
This is not a stats issue.  It is an Eligius issue.  And you not continuing to mine to pay off the overage defrauds the pool.

**Comment by wizkid057** [comment]
This was announced and described here: https://bitcointalk.org/index.php?topic=23768.msg4196568#msg4196568

**Comment by vtsuei2** [comment]
Thanks for the reply,

I didn't see that post, so I had no idea if my mining was actually repaying
the pool. I've switched my miners back.
I know the mining community is sort of toxic, but I hope you don't
automatically assume that everyone is a douchebag.

A late happy new year,
vtsuei2

**Comment by wizkid057** [comment]
I admittedly tend to assume the worst, especially when it comes to mixing money and anonymity.  Apologies for coming off harsh.  And thank you.
